### ISSUE TITLE
Nice 

### ISSUE THREAD

**Issue by skullcheat** [EquinoxAlpha/ayypex-ext#1]
Thank you for your fucking sharing I can't wait :D Love you :P

**Comment by skullcheat** [comment]
any new ? :)

**Comment by EquinoxAlpha** [comment]
Sorry for the long wait, the new season broke some things and I don't really play Apex much anymore.
I'll try to get it fixed by tomorrow, if not, I'll just release the code as-is.
Recoil control works, aim assist, triggerbot, and glow are currently broken.
After that, I'll probably take a break from updating this as I mentioned above that I don't really play Apex anymore.

**Comment by EquinoxAlpha** [comment]
new repository link is in readme because VSCode github integration is a bit dumb
